### PR TITLE
Add authentication

### PR DESCRIPTION
**Pull request by modmoto**

### CODE REVIEW

**Comment by abeninski** [comment]
Note that we need blizzard auth with china id as well

**Comment by modmoto** [comment]
Good point. Do you know how we could test that? According to the specs, the oauth worklflow works everywhere, selecting the gateway only changes the response time. But could be possible that we have issues in china then. That should be avoided of course.

**Comment by abeninski** [comment]
There is a separate endpoint for china 
image
https://develop.battle.net/documentation/guides/using-oauth
https://develop.battle.net/documentation/battle-net/oauth-apis-cn

**Comment by modmoto** [comment]
ah great, thanks for that.

**Comment by modmoto** [comment]
Do you have a cn account? Because I think they are authenticating against netease in the background. At least I can not use my EU account for china. Do you know if they can login on the EU URL? I mean this also would be a problem on the website and should be fixed.

**Comment by abeninski** [comment]
They cannot login with on eu for sure. @fluxxu might be able to help with this

**Comment by modmoto** [comment]
gonna built this to test with cn guys

**Pull request merged**
